'use client';

import localFont from "next/font/local";
import "./globals.css";
import NavbarComp from "./NavComp";
import { ApolloClient, InMemoryCache, ApolloProvider, gql } from '@apollo/client';

const client = new ApolloClient({
    uri: 'https://bookmanager-backend-production.up.railway.app/graphql',
    cache: new InMemoryCache(),
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarComp>
          <ApolloProvider client={client}>
            {children}
          </ApolloProvider>
        </NavbarComp>
      </body>
    </html>
  );
}
